version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=anywallet
  api-command:
    build: api.Dockerfile
    container_name: cqrs-api-command
    ports:
      - "8081:8080"
    environment:
      - CQRS_MODE=QUERY
  api-query:
    build: api.Dockerfile
    container_name: cqrs-api-query
    ports:
      - "8082:8080"
    environment:
      - CQRS_MODE=QUERY
      - DATABASE_ENDPOINT=""jdbc:postgresql://localhost:5432/anywallet"
      - DATABASE_USER_NAME="dev"
      - DATABASE_PASSWORD="password"
volumes:
  db-store:
